#cloudconfig
#

coreos:
    update:
        reboot-strategy: reboot
    etcd2:
        discovery:
        advertise-client-urls: http://0.0.0.0:2379
        initial-advertise-peer-urls: http://$private_ipv4:2380
        listen-client-urls: http://0.0.0.0:2379
        listen-peer-urls: http://0.0.0.0:2380
        heartbeat-interval: 10
        election-timeout: 50
    units:
        - name: etcd2.service
          command: start
